from typing import Protocol

class ProtocolRepository(Protocol):
    def save(self)->None:
        ...
    def delete(self)->None:
        ...
    def update(self)->None:
        ...
    def get_all(self)->None:
        ...
    def get_by_id(self)->None:
        ...